### ISSUE TITLE
Allow Extracting Periodic Frames

### ISSUE THREAD

**Issue by NateRedding** [transitive-bullshit/ffmpeg-extract-frames#1]
Nice, simple module!

My use case calls for extracting a frame periodically throughout the run of the file. (ie. once a second) It would be nice if this tool allowed you to do so more easily.

At the moment, I do this with the ffmpeg command:

        ffmpeg -i "path/to/file" -r 1 "dest/output_file_name_%04d.jpg"

Thoughts on adding this as a feature?

**Comment by transitive-bullshit** [comment]
Hey Nate, this is a great use case -- thanks for bringing it up!

I just added support for this as well as a few more use cases in `v2.0.0`. This should now do what you want:

```js
const extractFrames = require('ffmpeg-extract-frames')

// extract 1 frame per second
await extractFrames({
  input: 'media/1.mp4',
  output: './screenshot-%d.jpg',
  fps: 1
})
```

I also recently published this related [module](https://github.com/transitive-bullshit/ffmpeg-generate-video-preview) which you may find useful.

**Comment by transitive-bullshit** [comment]
btw, if you end up using this module, add a star to help others find it 😄

**Comment by NateRedding** [comment]
Wow that was fast, and it works like a charm! Thanks!
