### ISSUE TITLE
Cannot find ffmpeg

### ISSUE THREAD

**Issue by Oein** [transitive-bullshit/ffmpeg-extract-frames#10]
(node:28276) UnhandledPromiseRejectionWarning: Error: Cannot find ffmpeg

How can I fix this error?

**Comment by sebasalvarado** [comment]
I have the same error, anyone has an idea?

**Comment by lionelagbohouto-aliznet** [comment]
You need to install ffmpeg on your server 
http://www.ffmpeg.org/
